name: kcalz
options:
  bundleIdPrefix: com.kcalz
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: "NZLG76C8AD"

targets:
  kcalz:
    type: application
    platform: iOS
    sources:
      - path: kcalz
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_CFBundleDisplayName: kcalz
        SWIFT_STRICT_CONCURRENCY: complete
    dependencies:
      - package: GRDB

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "7.0.0"
